FROM amazoncorretto:8-alpine3.16-jdk

COPY aline-bank-microservice/bank-microservice/target/bank-microservice-0.1.0.jar /usr/src/

WORKDIR /usr/src/

# Set the start script as the entrypoint
ENTRYPOINT ["java", "-jar", "bank-microservice-0.1.0.jar"]
